#ifndef INCUNEST_PID_REFERENCE_H
#define INCUNEST_PID_REFERENCE_H

#define INCUNEST_PID_TEMP_KP 3.5f
#define INCUNEST_PID_TEMP_KI 0.35f
#define INCUNEST_PID_TEMP_KD 0.9f

#define INCUNEST_PID_HUM_KP 2.0f
#define INCUNEST_PID_HUM_KI 0.1f
#define INCUNEST_PID_HUM_KD 0.2f

#endif
